version: "3"
services:
  server:
    build:
      context: ./node
      dockerfile: ./Dockerfile
  auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
    ports:
      - 4180:4180
    volumes:
      - ./proxy-alpha-config.yaml:/conf/proxy-alpha-config.yaml:ro
      - ./proxy-config.cfg:/conf/proxy-config.cfg:ro
    command: --config /conf/proxy-config.cfg --alpha-config /conf/proxy-alpha-config.yaml
